name: CD PipeLine

on:
  push:
    branches:
      - main

jobs:
  deploy_to_ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

      # SSH PEM 키 설정
    - name: Set up PEM file for SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM_KEY }}" > ~/.ssh/student13.pem
        chmod 600 ~/.ssh/student13.pem
        
      # ec2에 연결하여 배포
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/student13.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/ec2-user/practice0930
        git pull origin main
        source .venv/bin/activate
        pip install -r requirements.txt
        uvicorn iference:app --host 0.0.0.0 