name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_to_ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    # SSH PEM 키 설정
    - name: Set up PEM file for SSH
      run: |
        echo "${{ secrets.EC2_PEM_KEY }}" > ~/student13.pem
        chmod 400 ~/student13.pem

    # EC2에 연결하여 배포
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/student13.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/practice0930
          git pull origin main
          source .venv/bin/activate
          pip install -r requirements.txt
          uvicorn inference:app --host 0.0.0.0 --port 8000
        EOF
